=== aittiphon123/lineage2/L2J_Mobius_CT_0_Interlude/dist/game/data/xsd/instance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="instance">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="activityTime" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger"
						              use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="allowSummon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="emptyDestroyTime" minOccurs="0"
				            maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger"
						              use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="PvPInstance" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="showTimer" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
						<xs:attribute name="increase" type="xs:boolean" use="optional" />
						<xs:attribute name="text" type="xs:normalizedString" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnPoints" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Location" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="x" type="xs:int" use="required" />
									<xs:attribute name="y" type="xs:int" use="required" />
									<xs:attribute name="z" type="xs:int" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="startPosType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="FIXED" />
									<xs:enumeration value="RANDOM" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="exitPoint" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="x" type="xs:int" use="required" />
						<xs:attribute name="y" type="xs:int" use="required" />
						<xs:attribute name="z" type="xs:int" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="reenter" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="reset" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="day">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="Monday" />
												<xs:enumeration value="Tuesday" />
												<xs:enumeration value="Wednesday" />
												<xs:enumeration value="Thursday" />
												<xs:enumeration value="Friday" />
												<xs:enumeration value="Saturday" />
												<xs:enumeration value="Sunday" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="time" type="xs:long" />
									<xs:attribute name="hour" type="xs:nonNegativeInteger" />
									<xs:attribute name="minute" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="additionStyle">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="NONE" />
									<xs:enumeration value="ON_ENTER" />
									<xs:enumeration value="ON_FINISH" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="removeBuffs" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="skill" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:integer" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="ALL" />
									<xs:enumeration value="WHITELIST" />
									<xs:enumeration value="BLACKLIST" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="doorlist" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="door" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger"
									              use="required" />
									<xs:attribute name="default_status">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="open" />
												<xs:enumeration value="close" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="random_time" type="xs:integer" />
									<xs:attribute name="open_time" type="xs:integer" />
									<xs:attribute name="close_time" type="xs:integer" />
									<xs:attribute name="level" type="xs:nonNegativeInteger" />
									<xs:attribute name="open_method" type="xs:nonNegativeInteger" />
									<xs:attribute name="targetable" type="xs:boolean" />
									<xs:attribute name="check_collision" type="xs:boolean" />
									<xs:attribute name="clanhall_id" type="xs:positiveInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnlist" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="group" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="amount" type="xs:positiveInteger" />
												<xs:attribute name="heading" type="xs:integer" />
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
												<xs:attribute name="onKillDelay" type="xs:nonNegativeInteger" />
												<xs:attribute name="respawn" type="xs:nonNegativeInteger" />
												<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" />
												<xs:attribute name="allowRandomWalk" type="xs:boolean" />
												<xs:attribute name="x" type="xs:integer" use="required" />
												<xs:attribute name="y" type="xs:integer" use="required" />
												<xs:attribute name="z" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:normalizedString"
									              use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger"
			              use="required" />
			<xs:attribute name="ejectTime" type="xs:positiveInteger" />
			<xs:attribute name="allowRandomWalk" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aittiphon123/lineage2/L2J_Mobius_Essence_09.2_RoseVain/dist/game/data/instances/TrainingZone.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance id="228" maxWorlds="125" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/instance.xsd">
	<time duration="60" empty="3" />
	<locations>
		<enter type="FIXED">
			<location x="-49375" y="17352" z="-3016" />
		</enter>
		<exit type="ORIGIN" />
	</locations>
	<conditions>
		<condition type="NoParty" />
		<condition type="Level">
			<param name="min" value="76" />
			<param name="max" value="99" />
		</condition>
		<condition type="Reenter" />
	</conditions>
	<reenter apply="ON_FINISH">
		<reset day="MONDAY" hour="6" minute="30" />
		<reset day="TUESDAY" hour="6" minute="30" />
		<reset day="WEDNESDAY" hour="6" minute="30" />
		<reset day="THURSDAY" hour="6" minute="30" />
		<reset day="FRIDAY" hour="6" minute="30" />
		<reset day="SATURDAY" hour="6" minute="30" />
		<reset day="SUNDAY" hour="6" minute="30" />
	</reenter>
	<spawnlist>
		<group>
			<!-- Start -->
			<npc id="34307" x="-49377" y="17548" z="-2984" heading="48000" respawnTime="30sec" /> <!-- Grown -->
			<npc id="34308" x="-49419" y="17513" z="-2984" heading="48000" respawnTime="30sec" /> <!-- Tind -->
			<npc id="34305" x="-49877" y="17640" z="-3016" heading="48000" respawnTime="30sec" /> <!-- Toka -->
			<npc id="34306" x="-49989" y="17640" z="-3016" heading="48000" respawnTime="30sec" /> <!-- Eri -->
			<npc id="34309" x="-50101" y="17640" z="-3016" heading="48000" respawnTime="30sec" /> <!-- Arbana -->
			<!-- Farm Zone -->
			<npc id="34305" x="-56573" y="13624" z="-3336" heading="56000" respawnTime="30sec" /> <!-- Toka -->
			<npc id="34306" x="-56285" y="13336" z="-3344" heading="24000" respawnTime="30sec" /> <!-- Eri -->
			<npc id="34308" x="-56189" y="13704" z="-3344" heading="40000" respawnTime="30sec" /> <!-- Tind -->
			<!-- Farm TOI Zone -->
			<npc id="34308" x="-52635" y="5167" z="-240" heading="8000" respawnTime="30sec" /> <!-- Tind -->
			<npc id="34305" x="-52346" y="4781" z="-240" heading="16000" respawnTime="30sec" /> <!-- Toka -->
			<npc id="34306" x="-53111" y="5442" z="-240" heading="2000" respawnTime="30sec" /> <!-- Eri -->
			<!-- Cruma -->
			<npc id="34310" x="-43669" y="9039" z="1136" heading="62153" respawnTime="15sec" /> <!-- Mercenary -->
			<npc id="34310" x="-43466" y="9525" z="1136" heading="62181" respawnTime="15sec" /> <!-- Mercenary -->
			<npc id="34306" x="-43491" y="9478" z="1136" heading="58604" respawnTime="15sec" /> <!-- Eri -->
			<npc id="34308" x="-43572" y="9294" z="1136" heading="61018" respawnTime="15sec" /> <!-- Tind -->
			<npc id="34305" x="-43647" y="9113" z="1136" heading="62249" respawnTime="15sec" /> <!-- Toka -->
			<!-- Mercenaries -->
			<npc id="34310" x="-52308" y="4870" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-52547" y="5040" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-52390" y="4881" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-52262" y="4835" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-52449" y="4825" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-52655" y="5032" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-52784" y="5206" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-52782" y="5121" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-53013" y="5379" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-53009" y="5490" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-53049" y="5332" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-53071" y="5544" z="-240" heading="8000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50246" y="5927" z="-240" heading="26000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50416" y="6382" z="-240" heading="35000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50371" y="6905" z="-240" heading="41000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-56205" y="13224" z="-3352" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-56301" y="13240" z="-3352" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-56397" y="13256" z="-3352" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-56077" y="13688" z="-3336" heading="42000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-56637" y="13480" z="-3344" heading="65000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-56125" y="13768" z="-3344" heading="42000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-56189" y="13816" z="-3344" heading="42000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-56669" y="13592" z="-3344" heading="65000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-56685" y="13704" z="-3344" heading="65000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49125" y="16552" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49045" y="16552" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48965" y="16552" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48885" y="16552" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49269" y="16664" z="-3192" heading="0" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48789" y="16552" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49125" y="16664" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48709" y="16552" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49045" y="16664" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48965" y="16664" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48885" y="16664" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48789" y="16664" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49125" y="16776" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48709" y="16664" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49045" y="16776" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48965" y="16776" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48885" y="16776" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48789" y="16776" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48709" y="16776" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50197" y="17240" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50117" y="17240" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50037" y="17240" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49957" y="17240" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49877" y="17240" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48709" y="16920" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49797" y="17240" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48629" y="16920" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50197" y="17352" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48549" y="16920" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50117" y="17352" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48869" y="17032" z="-3192" heading="0" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50037" y="17352" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48469" y="16920" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49957" y="17352" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48373" y="16920" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49877" y="17352" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48709" y="17032" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-49797" y="17352" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48293" y="16920" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48629" y="17032" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50197" y="17464" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48549" y="17032" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-50117" y="17464" z="-3016" heading="16000" respawnTime="30sec" /> <!-- Mercenary -->
			<npc id="34310" x="-48469" y="17032" z="-3192" heading="32000" respawnTime="30sec" /> <!-- Mercenary -->
