=== aittiphon123/lineage2/L2J_Mobius_01.0_Ertheia/dist/game/data/xsd/playerTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="classId" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:minInclusive value="0" />
							<xs:maxInclusive value="189" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="staticData" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element type="xs:nonNegativeInteger" name="baseINT" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseSTR" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseCON" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseMEN" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseDEX" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseWIT" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseLUC" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:nonNegativeInteger" name="baseCHA" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:integer" name="physicalAbnormalResist" minOccurs="0" maxOccurs="1" />
							<xs:element type="xs:integer" name="magicAbnormalResist" minOccurs="0" maxOccurs="1" />
							<xs:element name="creationPoints" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="0">
										<xs:element name="node" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:attribute type="xs:integer" name="x" use="required" />
												<xs:attribute type="xs:integer" name="y" use="required" />
												<xs:attribute type="xs:integer" name="z" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtk" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseCritRate" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseMCritRate" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="basePSkillCritRate" minOccurs="0" maxOccurs="1" />
							<xs:element name="baseAtkType" minOccurs="1" maxOccurs="1">
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:enumeration value="FIST" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtkSpd" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseMAtkSpd" minOccurs="0" maxOccurs="1" />
							<xs:element name="basePDef" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="chest" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="legs" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="head" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="feet" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="gloves" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="underwear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="cloak" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseMAtk" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseMDef" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="rear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="lear" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="rfinger" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="lfinger" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="neck" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:nonNegativeInteger" name="baseCanPenetrate" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseAtkRange" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseDamRange" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:nonNegativeInteger" name="verticalDirection" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="horizontalDirection" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="distance" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:nonNegativeInteger" name="width" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseRndDam" minOccurs="1" maxOccurs="1" />
							<xs:element name="baseMoveSpd" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:positiveInteger" name="walk" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="run" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="slowSwim" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:positiveInteger" name="fastSwim" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseBreath" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:positiveInteger" name="baseSafeFall" minOccurs="1" maxOccurs="1" />
							<xs:element name="collisionMale" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="radius" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="height" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="collisionFemale" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="radius" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="height" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="lvlUpgainData" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="level" maxOccurs="99" minOccurs="99">
								<xs:complexType>
									<xs:sequence maxOccurs="1" minOccurs="1">
										<xs:element type="xs:decimal" name="hp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="mp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="cp" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="hpRegen" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="mpRegen" minOccurs="1" maxOccurs="1" />
										<xs:element type="xs:decimal" name="cpRegen" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="val" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
												<xs:maxInclusive value="99" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aittiphon123/lineage2/L2J_Mobius_04.0_GrandCrusade/dist/game/data/stats/players/templates/3rdClass/Soultaker.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../xsd/playerTemplate.xsd">
	<classId>95</classId>
	<staticData>
		<baseINT>79</baseINT>
		<baseSTR>38</baseSTR>
		<baseCON>41</baseCON>
		<baseMEN>78</baseMEN>
		<baseDEX>27</baseDEX>
		<baseWIT>78</baseWIT>
		<baseLUC>34</baseLUC>
		<baseCHA>41</baseCHA>
		<physicalAbnormalResist>10</physicalAbnormalResist>
		<magicAbnormalResist>10</magicAbnormalResist>
		<creationPoints>
			<node x="-114628" y="259915" z="-1192" />
			<node x="-114539" y="260101" z="-1192" />
			<node x="-114376" y="260165" z="-1192" />
			<node x="-114213" y="260019" z="-1192" />
			<node x="-114452" y="259908" z="-1192" />
		</creationPoints>
		<basePAtk>3</basePAtk>
		<baseCritRate>4</baseCritRate>
		<baseMCritRate>5</baseMCritRate>
		<basePSkillCritRate>5</basePSkillCritRate>
		<baseAtkType>FIST</baseAtkType>
		<basePAtkSpd>300</basePAtkSpd>
		<baseMAtkSpd>333</baseMAtkSpd>
		<basePDef>
			<chest>15</chest>
			<legs>8</legs>
			<head>12</head>
			<feet>7</feet>
			<gloves>8</gloves>
			<underwear>3</underwear>
			<cloak>1</cloak>
		</basePDef>
		<baseMAtk>6</baseMAtk>
		<baseMDef>
			<rear>9</rear>
			<lear>9</lear>
			<rfinger>5</rfinger>
			<lfinger>5</lfinger>
			<neck>13</neck>
		</baseMDef>
		<baseCanPenetrate>0</baseCanPenetrate>
		<baseAtkRange>20</baseAtkRange>
		<baseDamRange>
			<verticalDirection>0</verticalDirection>
			<horizontalDirection>0</horizontalDirection>
			<distance>26</distance>
			<width>120</width>
		</baseDamRange>
		<baseRndDam>10</baseRndDam>
		<baseMoveSpd>
			<walk>78</walk>
			<run>124</run>
			<slowSwim>50</slowSwim>
			<fastSwim>50</fastSwim>
		</baseMoveSpd>
		<baseBreath>100</baseBreath>
		<baseSafeFall>200</baseSafeFall>
		<collisionMale>
			<radius>9.0</radius>
			<height>23</height>
		</collisionMale>
		<collisionFemale>
			<radius>8.0</radius>
			<height>23.5</height>
		</collisionFemale>
	</staticData>
	<lvlUpgainData>
		<level val="1">
			<hp>101.0</hp>
			<mp>40.0</mp>
			<cp>50.5</cp>
			<hpRegen>2.0</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="2">
			<hp>116.47</hp>
			<mp>47.28</mp>
			<cp>58.235</cp>
			<hpRegen>2.05</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="3">
			<hp>132.11</hp>
			<mp>54.64</mp>
			<cp>66.055</cp>
			<hpRegen>2.1</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="4">
			<hp>147.92</hp>
			<mp>62.08</mp>
			<cp>73.96</cp>
			<hpRegen>2.15</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="5">
			<hp>163.9</hp>
			<mp>69.6</mp>
			<cp>81.95</cp>
			<hpRegen>2.2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="6">
			<hp>180.05</hp>
			<mp>77.2</mp>
			<cp>90.025</cp>
			<hpRegen>2.25</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="7">
			<hp>196.37</hp>
			<mp>84.88</mp>
			<cp>98.185</cp>
			<hpRegen>2.3</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="8">
			<hp>212.86</hp>
			<mp>92.64</mp>
			<cp>106.43</cp>
			<hpRegen>2.35</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="9">
			<hp>229.52</hp>
			<mp>100.48</mp>
			<cp>114.76</cp>
			<hpRegen>2.4</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="10">
			<hp>246.35</hp>
			<mp>108.4</mp>
			<cp>123.175</cp>
			<hpRegen>2.45</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="11">
			<hp>263.35</hp>
			<mp>116.4</mp>
			<cp>131.675</cp>
			<hpRegen>2.5</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="12">
			<hp>280.52</hp>
			<mp>124.48</mp>
			<cp>140.26</cp>
			<hpRegen>2.6</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="13">
			<hp>297.86</hp>
			<mp>132.64</mp>
			<cp>148.93</cp>
			<hpRegen>2.7</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="14">
			<hp>315.37</hp>
			<mp>140.88</mp>
			<cp>157.685</cp>
			<hpRegen>2.8</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="15">
			<hp>333.05</hp>
			<mp>149.2</mp>
			<cp>166.525</cp>
			<hpRegen>2.9</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="16">
			<hp>350.9</hp>
			<mp>157.6</mp>
			<cp>175.45</cp>
			<hpRegen>3.0</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="17">
			<hp>368.92</hp>
			<mp>166.08</mp>
			<cp>184.46</cp>
			<hpRegen>3.1</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="18">
			<hp>387.11</hp>
			<mp>174.64</mp>
			<cp>193.555</cp>
			<hpRegen>3.2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="19">
			<hp>405.47</hp>
			<mp>183.28</mp>
			<cp>202.735</cp>
			<hpRegen>3.3</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="20">
			<hp>424.0</hp>
			<mp>192.0</mp>
			<cp>212.0</cp>
			<hpRegen>3.4</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="21">
			<hp>451.5</hp>
			<mp>205.2</mp>
			<cp>225.75</cp>
			<hpRegen>3.5</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="22">
			<hp>479.25</hp>
			<mp>218.52</mp>
			<cp>239.625</cp>
			<hpRegen>3.6</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="23">
			<hp>507.25</hp>
			<mp>231.96</mp>
			<cp>253.625</cp>
			<hpRegen>3.7</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="24">
			<hp>535.5</hp>
			<mp>245.52</mp>
			<cp>267.75</cp>
			<hpRegen>3.8</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="25">
			<hp>564.0</hp>
			<mp>259.2</mp>
			<cp>282.0</cp>
			<hpRegen>3.9</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="26">
			<hp>592.75</hp>
			<mp>273.0</mp>
			<cp>296.375</cp>
			<hpRegen>4.0</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="27">
			<hp>621.75</hp>
			<mp>286.92</mp>
			<cp>310.875</cp>
			<hpRegen>4.1</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="28">
			<hp>651.0</hp>
			<mp>300.96</mp>
			<cp>325.5</cp>
			<hpRegen>4.2</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="29">
			<hp>680.5</hp>
			<mp>315.12</mp>
			<cp>340.25</cp>
			<hpRegen>4.3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="30">
			<hp>710.25</hp>
			<mp>329.4</mp>
			<cp>355.125</cp>
			<hpRegen>4.4</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="31">
			<hp>740.25</hp>
			<mp>343.8</mp>
			<cp>370.125</cp>
			<hpRegen>4.5</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="32">
			<hp>770.5</hp>
			<mp>358.32</mp>
			<cp>385.25</cp>
			<hpRegen>4.6</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="33">
			<hp>801.0</hp>
			<mp>372.96</mp>
			<cp>400.5</cp>
			<hpRegen>4.7</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="34">
			<hp>831.75</hp>
			<mp>387.72</mp>
			<cp>415.875</cp>
			<hpRegen>4.8</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="35">
			<hp>862.75</hp>
			<mp>402.6</mp>
			<cp>431.375</cp>
			<hpRegen>4.9</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="36">
			<hp>894.0</hp>
			<mp>417.6</mp>
			<cp>447.0</cp>
			<hpRegen>5.0</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="37">
			<hp>925.5</hp>
			<mp>432.72</mp>
			<cp>462.75</cp>
			<hpRegen>5.1</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="38">
			<hp>957.25</hp>
			<mp>447.96</mp>
			<cp>478.625</cp>
			<hpRegen>5.2</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="39">
			<hp>989.25</hp>
			<mp>463.32</mp>
			<cp>494.625</cp>
			<hpRegen>5.3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="40">
			<hp>1021.5</hp>
			<mp>478.8</mp>
			<cp>510.75</cp>
			<hpRegen>5.4</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="41">
			<hp>1067.0</hp>
			<mp>504.8</mp>
			<cp>533.5</cp>
			<hpRegen>5.5</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="42">
			<hp>1112.85</hp>
			<mp>531.0</mp>
			<cp>556.425</cp>
			<hpRegen>5.6</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="43">
			<hp>1159.05</hp>
			<mp>557.4</mp>
			<cp>579.525</cp>
			<hpRegen>5.7</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="44">
			<hp>1205.6</hp>
			<mp>584.0</mp>
			<cp>602.8</cp>
			<hpRegen>5.8</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="45">
			<hp>1252.5</hp>
			<mp>610.8</mp>
			<cp>626.25</cp>
			<hpRegen>5.9</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="46">
			<hp>1299.75</hp>
			<mp>637.8</mp>
			<cp>649.875</cp>
			<hpRegen>6.0</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="47">
			<hp>1347.35</hp>
			<mp>665.0</mp>
			<cp>673.675</cp>
			<hpRegen>6.1</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="48">
			<hp>1395.3</hp>
			<mp>692.4</mp>
			<cp>697.65</cp>
			<hpRegen>6.2</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="49">
			<hp>1443.6</hp>
			<mp>720.0</mp>
			<cp>721.8</cp>
			<hpRegen>6.3</hpRegen>
