=== aittiphon123/lineage2/L2J_Mobius_Essence_07.3_SevenSigns/dist/game/data/xsd/items.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="item">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element maxOccurs="unbounded" name="set">
									<xs:complexType>
										<xs:attribute name="name" type="xs:string" use="required" />
										<xs:attribute name="val" type="xs:string" use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element name="skills">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="skill">
												<xs:complexType>
													<xs:attribute name="id" type="xs:int" use="required" />
													<xs:attribute name="level" type="xs:unsignedByte" use="required" />
													<xs:attribute name="subLevel" type="xs:unsignedShort" use="optional" />
													<xs:attribute name="type" type="xs:string" use="optional" />
													<xs:attribute name="type_value" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="type_chance" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="stats">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="stat">
												<xs:complexType>
													<xs:simpleContent>
														<xs:extension base="xs:decimal">
															<xs:attribute name="type" type="xs:string" use="required" />
														</xs:extension>
													</xs:simpleContent>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="conditions">
									<xs:complexType>
										<xs:sequence>
											<xs:element minOccurs="0" name="target">
												<xs:complexType>
													<xs:attribute name="levelRange" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="and">
												<xs:complexType>
													<xs:sequence>
														<xs:element maxOccurs="unbounded" name="player">
															<xs:complexType>
																<xs:attribute name="castle" type="xs:byte" use="optional" />
																<xs:attribute name="pledgeClass" type="xs:byte" use="optional" />
																<xs:attribute name="sex" type="xs:unsignedByte" use="optional" />
																<xs:attribute name="class_id_restriction" type="xs:string" use="optional" />
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="player">
												<xs:complexType>
													<xs:attribute name="flyMounted" type="xs:boolean" use="optional" />
													<xs:attribute name="isHero" type="xs:boolean" use="optional" />
													<xs:attribute name="sex" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="level" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="chaotic" type="xs:boolean" use="optional" />
													<xs:attribute name="levelRange" type="xs:string" use="optional" />
													<xs:attribute name="insideZoneId" type="xs:string" use="optional" />
													<xs:attribute name="class_id_restriction" type="xs:string" use="optional" />
													<xs:attribute name="categoryType" type="xs:string" use="optional" />
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="not">
												<xs:complexType>
													<xs:sequence>
														<xs:element maxOccurs="unbounded" name="player">
															<xs:complexType>
																<xs:attribute name="active_effect_id" type="xs:unsignedShort" use="optional" />
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="addName" type="xs:unsignedByte" use="optional" />
										<xs:attribute name="msgId" type="xs:unsignedShort" use="optional" />
									</xs:complexType>
								</xs:element>
								<xs:element name="capsuled_items">
									<xs:complexType mixed="true">
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="item">
												<xs:complexType>
													<xs:attribute name="id" type="xs:integer" use="required" />
													<xs:attribute name="min" type="xs:unsignedLong" use="required" />
													<xs:attribute name="max" type="xs:unsignedLong" use="required" />
													<xs:attribute name="chance" type="xs:decimal" use="required" />
													<xs:attribute name="minEnchant" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="maxEnchant" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedInt" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="additionalName" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aittiphon123/lineage2/L2J_Mobius_Essence_07.3_SevenSigns/dist/game/data/stats/items/05200-05299.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="5200" name="Chest Key - Grade 5" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Opens a level 30 treasure chest with a success rate of 60%. When opening a higher level treasure chest, the success rate will decrease. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="10" />
		<set name="price" val="1900" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<skills>
			<skill id="2065" level="4" /> <!-- Box Key -->
		</skills>
	</item>
	<item id="5201" name="Chest Key - Grade 4" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Opens a level 40 treasure chest with a success rate of 60%. When opening a higher level treasure chest, the success rate will decrease. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="10" />
		<set name="price" val="3200" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<skills>
			<skill id="2065" level="5" /> <!-- Box Key -->
		</skills>
	</item>
	<item id="5202" name="Chest Key - Grade 3" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Opens a level 50 treasure chest with a success rate of 60%. When opening a higher level treasure chest, the success rate will decrease. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="10" />
		<set name="price" val="5100" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<skills>
			<skill id="2065" level="6" /> <!-- Box Key -->
		</skills>
	</item>
	<item id="5203" name="Chest Key - Grade 2" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Opens a level 60 treasure chest with a success rate of 60%. When opening a higher level treasure chest, the success rate will decrease. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="10" />
		<set name="price" val="7400" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<skills>
			<skill id="2065" level="7" /> <!-- Box Key -->
		</skills>
	</item>
	<item id="5204" name="Chest Key - Grade 1" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Opens a level 70 treasure chest with a success rate of 60%. When opening a higher level treasure chest, the success rate will decrease. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="10" />
		<set name="price" val="10000" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<skills>
			<skill id="2065" level="8" /> <!-- Box Key -->
		</skills>
	</item>
	<item id="5205" name="Mercenary Posting Ticket (Sword/Stationary)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/Sword/Stationary. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="50000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5206" name="Mercenary Posting Ticket (Spear/Stationary)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/Spear/Stationary. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="60000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5207" name="Mercenary Posting Ticket (Bow/Stationary)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/Bow/Stationary. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="70000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5208" name="Mercenary Posting Ticket (Cleric/Stationary)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/ Healer/ Stationary. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="170000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5209" name="Mercenary Posting Ticket (Wizard/Stationary)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/Wizard/Stationary -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="170000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5210" name="Mercenary Posting Ticket (Sword/ Mobile)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/ Sword/ Mobile. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="50000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5211" name="Mercenary Posting Ticket (Spear/ Mobile)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/ Spear/ Mobile. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="60000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5212" name="Mercenary Posting Ticket (Bow/ Mobile)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/ Bow/ Mobile. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="70000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5213" name="Mercenary Posting Ticket (Cleric/ Mobile)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/ Healer/ Mobile. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="170000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5214" name="Mercenary Posting Ticket (Wizard/Mobile)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/Wizard/Mobile -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="170000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5215" name="Mercenary Posting Ticket (Teleporter1)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/Teleporter/Inner Castle, Guard -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="etcitem_type" val="CASTLE_GUARD" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="price" val="100000" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="handler" val="MercTicket" />
	</item>
	<item id="5218" name="Mercenary Posting Ticket (Teleporter2)" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Innadril/Teleporter/Outer Castle, Guardian -->
		<set name="icon" val="icon.etc_ertheia2" />
