=== aittiphon123/lineage2/L2J_Mobius_Classic_2.9.5_Saviors/dist/game/data/xsd/items.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="skillsType">
		<xs:sequence>
			<xs:element name="skill" type="skillType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="unequipSkillsType">
		<xs:sequence>
			<xs:element name="skill" type="skillType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="capsuledItemsType">
		<xs:sequence>
			<xs:element name="item" type="capsuledItemType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="skillType">
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="level" type="xs:positiveInteger" use="required" />
		<xs:attribute name="subLevel" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="NORMAL" />
					<xs:enumeration value="ON_ENCHANT" />
					<xs:enumeration value="ON_EQUIP" />
					<xs:enumeration value="ON_UNEQUIP" />
					<xs:enumeration value="ON_CRITICAL_SKILL" />
					<xs:enumeration value="ON_MAGIC_SKILL" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="type_chance" type="xs:positiveInteger" />
		<xs:attribute name="type_value" type="xs:positiveInteger" />
	</xs:complexType>

	<xs:complexType name="capsuledItemType">
		<xs:attribute name="id" type="xs:positiveInteger" />
		<xs:attribute name="min" type="xs:positiveInteger" />
		<xs:attribute name="max" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:double" />
		<xs:attribute name="minEnchant" type="xs:positiveInteger" use="optional" />
		<xs:attribute name="maxEnchant" type="xs:positiveInteger" use="optional" />
	</xs:complexType>

	<xs:complexType name="createItemType">
		<xs:attribute name="id" type="xs:positiveInteger" />
		<xs:attribute name="count" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:double" />
	</xs:complexType>

	<xs:complexType name="setType">
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="displayId" />
					<xs:enumeration value="armor_type" />
					<xs:enumeration value="attack_range" />
					<xs:enumeration value="auto_destroy_time" />
					<xs:enumeration value="blessed" />
					<xs:enumeration value="bodypart" />
					<xs:enumeration value="capsuled_items" />
					<xs:enumeration value="change_weaponId" />
					<xs:enumeration value="crystal_count" />
					<xs:enumeration value="crystal_type" />
					<xs:enumeration value="damage_range" />
					<xs:enumeration value="default_action" />
					<xs:enumeration value="duration" />
					<xs:enumeration value="element_enabled" />
					<xs:enumeration value="enchant_enabled" />
					<xs:enumeration value="enchant_limit" />
					<xs:enumeration value="enchant4_skill" />
					<xs:enumeration value="enchanted" />
					<xs:enumeration value="equip_condition" />
					<xs:enumeration value="equip_reuse_delay" />
					<xs:enumeration value="ex_immediate_effect" />
					<xs:enumeration value="extractableCountMin" />
					<xs:enumeration value="extractableCountMax" />
					<xs:enumeration value="etcitem_type" />
					<xs:enumeration value="for_npc" />
					<xs:enumeration value="handler" />
					<xs:enumeration value="icon" />
					<xs:enumeration value="immediate_effect" />
					<xs:enumeration value="is_depositable" />
					<xs:enumeration value="is_destroyable" />
					<xs:enumeration value="is_dropable" />
					<xs:enumeration value="is_freightable" />
					<xs:enumeration value="is_magic_weapon" />
					<xs:enumeration value="is_oly_restricted" />
					<xs:enumeration value="is_event_restricted" />
					<xs:enumeration value="isAppearanceable" />
					<xs:enumeration value="ensoulNormalSlots" />
					<xs:enumeration value="ensoulSpecialSlots" />
					<xs:enumeration value="is_premium" />
					<xs:enumeration value="is_questitem" />
					<xs:enumeration value="is_sellable" />
					<xs:enumeration value="is_stackable" />
					<xs:enumeration value="is_tradable" />
					<xs:enumeration value="is_infinite" />
					<xs:enumeration value="is_commissionable" />
					<xs:enumeration value="is_mailable" />
					<xs:enumeration value="is_clan_depositable" />
					<xs:enumeration value="is_private_storeable" />
					<xs:enumeration value="isAttackWeapon" />
					<xs:enumeration value="isForceEquip" />
					<xs:enumeration value="item_skill" />
					<xs:enumeration value="allow_self_resurrection" />
					<xs:enumeration value="material" />
					<xs:enumeration value="mp_consume" />
					<xs:enumeration value="oncrit_chance" />
					<xs:enumeration value="oncrit_skill" />
					<xs:enumeration value="onmagic_chance" />
					<xs:enumeration value="onmagic_skill" />
					<xs:enumeration value="price" />
					<xs:enumeration value="random_damage" />
					<xs:enumeration value="recipe_id" />
					<xs:enumeration value="reduced_mp_consume" />
					<xs:enumeration value="reduced_soulshot" />
					<xs:enumeration value="reuse_delay" />
					<xs:enumeration value="shared_reuse_group" />
					<xs:enumeration value="soulshots" />
					<xs:enumeration value="spiritshots" />
					<xs:enumeration value="time" />
					<xs:enumeration value="unequip_skill" />
					<xs:enumeration value="use_condition" />
					<xs:enumeration value="useSkillDisTime" />
					<xs:enumeration value="useWeaponSkillsOnly" />
					<xs:enumeration value="weapon_type" />
					<xs:enumeration value="weight" />
					<xs:enumeration value="commissionItemType" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="val" type="xs:token" use="required" />
	</xs:complexType>
	<xs:complexType name="playerType">
		<xs:attribute name="castle">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="-1" />
					<xs:maxInclusive value="9" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="isOnSide" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="NEUTRAL" />
					<xs:enumeration value="LIGHT" />
					<xs:enumeration value="DARK" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="isClanLeader" type="xs:boolean" />
		<xs:attribute name="clanHall" type="xs:normalizedString" />
		<xs:attribute name="class_id_restriction" type="xs:normalizedString" />
		<xs:attribute name="cloakStatus" type="xs:boolean" />
		<xs:attribute name="isHero" type="xs:boolean" />
		<xs:attribute name="isPvpFlagged" type="xs:boolean" />
		<xs:attribute name="insideZoneId" type="xs:normalizedString" />
		<xs:attribute name="level">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger">
					<xs:minInclusive value="1" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="pledgeClass">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="-1" />
					<xs:maxInclusive value="11" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="levelRange" type="xs:token" />
		<xs:attribute name="races" type="xs:token" />
		<xs:attribute name="sex" type="xs:byte" use="optional" />
		<xs:attribute name="fort" type="xs:integer" />
		<xs:attribute name="chaotic" type="xs:boolean" />
		<xs:attribute name="subclass" type="xs:boolean" />
		<xs:attribute name="SiegeZone" type="xs:positiveInteger" />
		<xs:attribute name="flyMounted" type="xs:boolean" />
		<xs:attribute name="instanceId" type="xs:normalizedString" />
		<xs:attribute name="categoryType" type="xs:normalizedString" />
		<xs:attribute name="pkCount" type="xs:int" />
		<xs:attribute name="vehicleMounted" type="xs:boolean" />
		<xs:attribute name="MinimumVitalityPoints" type="xs:int" />
	</xs:complexType>
	<xs:complexType name="andType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
			<xs:element name="not" type="notType" />
			<xs:element name="game" type="gameType" />
			<xs:element name="or" minOccurs="0" type="andType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="gameType">
		<xs:attribute type="xs:string" name="night" />
	</xs:complexType>
	<xs:complexType name="notType">
		<xs:sequence>
			<xs:element name="using" minOccurs="0" type="usingType" />
			<xs:element name="player" minOccurs="0" type="playerType" />
			<xs:element name="target" minOccurs="0" type="targetType" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="usingType">
		<xs:attribute type="xs:string" name="kind" use="optional" />
		<xs:attribute type="xs:string" name="slot" use="optional" />
		<xs:attribute type="xs:string" name="weaponChange" use="optional" />
	</xs:complexType>
	<xs:complexType name="targetType">
		<xs:attribute name="levelRange" type="xs:token" />
		<xs:attribute name="categoryType" type="xs:normalizedString" />
	</xs:complexType>
	<xs:complexType name="enchantType">
		<xs:attribute name="order" type="xs:byte" use="optional" />
		<xs:attribute name="stat" use="required" type="statType" />
		<xs:attribute name="val" type="xs:integer" fixed="0" use="required" />
	</xs:complexType>
	<xs:simpleType name="statType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="mAtk" />
			<xs:enumeration value="mDef" />
			<xs:enumeration value="pAtk" />
			<xs:enumeration value="pDef" />
			<xs:enumeration value="sDef" />
			<xs:enumeration value="mAtk" />
			<xs:enumeration value="pAtkAngle" />
			<xs:enumeration value="pAtkRange" />
			<xs:enumeration value="pAtkSpd" />
			<xs:enumeration value="critRate" />
			<xs:enumeration value="mCritRate" />
			<xs:enumeration value="rShld" />
			<xs:enumeration value="rEvas" />
			<xs:enumeration value="mEvas" />
			<xs:enumeration value="accCombat" />
			<xs:enumeration value="accMagic" />
			<xs:enumeration value="darkRes" />
			<xs:enumeration value="earthRes" />
			<xs:enumeration value="fireRes" />
			<xs:enumeration value="holyPower" />
			<xs:enumeration value="holyRes" />
			<xs:enumeration value="maxMp" />
			<xs:enumeration value="waterRes" />
			<xs:enumeration value="windRes" />
			<xs:enumeration value="magicSuccRes" />
			<xs:enumeration value="moveSpeed" />
			<xs:enumeration value="broochJewels" />
			<xs:enumeration value="inventoryLimit" />
			<xs:enumeration value="randomDamage" />
			<xs:enumeration value="firePower" />
			<xs:enumeration value="waterPower" />
			<xs:enumeration value="windPower" />
			<xs:enumeration value="earthPower" />
			<xs:enumeration value="holyPower" />
			<xs:enumeration value="darkPower" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="condType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="and" type="andType" />
			<xs:element name="not" type="notType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
		</xs:choice>
		<xs:attribute type="xs:short" name="msgId" use="optional" />
		<xs:attribute type="xs:byte" name="addName" use="optional" />
		<xs:attribute type="xs:string" name="msg" use="optional" />
	</xs:complexType>
	<xs:complexType name="forType" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="stat" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute type="statType" name="type" use="required" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="enchant" maxOccurs="2" minOccurs="0" type="enchantType" />
		</xs:choice>
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:byte" name="val" use="optional" />
	</xs:complexType>
	<xs:complexType name="itemType">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element name="set" maxOccurs="unbounded" minOccurs="1" type="setType" />
			<xs:element name="unequip_skills" minOccurs="0" type="skillsType" />
			<xs:element name="capsuled_items" minOccurs="0" type="capsuledItemsType" />
			<xs:element name="conditions" maxOccurs="2" minOccurs="0" type="condType" />
			<xs:element name="stats" maxOccurs="1" minOccurs="0" type="forType" />
			<xs:element name="skills" minOccurs="0" type="skillsType" />
		</xs:sequence>
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger">
					<xs:minInclusive value="1" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="name" type="xs:normalizedString" use="required" />
		<xs:attribute name="additionalName" type="xs:normalizedString" use="optional" />
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="Armor" />
					<xs:enumeration value="EtcItem" />
					<xs:enumeration value="Weapon" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="itemType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aittiphon123/lineage2/L2J_Mobius_Classic_2.9.5_Saviors/dist/game/data/stats/items/90600-90699.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="90600" name="Yul's Rune - Stage 7" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_yr_lv02" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90601" name="Yul's Rune - Stage 8" additionalName="Super" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_yr_lv02" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90602" name="Yul's Rune - Stage 9" additionalName="Super" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_yr_lv02" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90603" name="Yul's Rune - Stage 10" additionalName="Super" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_yr_lv02" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90604" name="Yul's Rune - Stage 11" additionalName="Super" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_yr_lv03" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90605" name="Yul's Rune - Stage 12" additionalName="Super" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_yr_lv03" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90606" name="Yul's Rune - Stage 13" additionalName="Super" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_yr_lv03" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90607" name="Yul's Rune - Stage 14" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_yr_lv03" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90608" name="Yul's Rune - Stage 15" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_yr_lv03" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90609" name="Yul's Rune - Stage 16" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="icon.ensoul_big_p" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90610" name="Yul's Rune - Stage 17" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="icon.ensoul_big_p" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90611" name="Yul's Rune - Stage 18" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="icon.ensoul_big_p" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90612" name="Yul's Rune - Stage 19" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="icon.ensoul_big_p" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90613" name="Yul's Rune - Stage 20" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="icon.ensoul_big_p" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90614" name="Feoh's Rune - Stage 1" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_feoh_lv01" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90615" name="Feoh's Rune - Stage 2" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_feoh_lv01" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90616" name="Feoh's Rune - Stage 3" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_feoh_lv01" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90617" name="Feoh's Rune - Stage 4" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_feoh_lv01" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90618" name="Feoh's Rune - Stage 5" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_feoh_lv01" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90619" name="Feoh's Rune - Stage 6" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_feoh_lv02" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90620" name="Feoh's Rune - Stage 7" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
		<set name="icon" val="BranchIcon.Icon.g_rune_feoh_lv02" />
		<set name="weight" val="20" />
		<set name="is_stackable" val="true" />
		<set name="material" val="CRYSTAL" />
	</item>
	<item id="90621" name="Feoh's Rune - Stage 8" additionalName="Super" type="EtcItem">
		<!-- A stone with a symbol of ancient Giants engraved. Can be Enchanted through Compounding to make a Top-grade Rune. If a top-rank blacksmith puts it in the slot, the weapon will be endowed with the Rune's power. -->
