=== aittiphon123/lineage2/L2J_Mobius_13.2_WolfWaker/dist/game/data/xsd/items.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="item">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element maxOccurs="unbounded" name="set">
									<xs:complexType>
										<xs:attribute name="name" type="xs:string" use="required" />
										<xs:attribute name="val" type="xs:string" use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element maxOccurs="unbounded" name="conditions">
									<xs:complexType>
										<xs:sequence>
											<xs:element minOccurs="0" name="target">
												<xs:complexType>
													<xs:attribute name="levelRange" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="and">
												<xs:complexType>
													<xs:sequence>
														<xs:element maxOccurs="unbounded" name="player">
															<xs:complexType>
																<xs:attribute name="castle" type="xs:byte" use="optional" />
																<xs:attribute name="pledgeClass" type="xs:byte" use="optional" />
																<xs:attribute name="races" type="xs:string" use="optional" />
																<xs:attribute name="clanHall" type="xs:byte" use="optional" />
																<xs:attribute name="isHero" type="xs:boolean" use="optional" />
																<xs:attribute name="categoryType" type="xs:string" use="optional" />
																<xs:attribute name="subclass" type="xs:boolean" use="optional" />
																<xs:attribute name="level" type="xs:unsignedByte" use="optional" />
																<xs:attribute name="subLevel" type="xs:unsignedShort" use="optional" />
																<xs:attribute name="cloakStatus" type="xs:boolean" use="optional" />
																<xs:attribute name="instanceId" type="xs:string" use="optional" />
																<xs:attribute name="isOnSide" type="xs:string" use="optional" />
																<xs:attribute name="isClanLeader" type="xs:boolean" use="optional" />
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="player">
												<xs:complexType>
													<xs:attribute name="flyMounted" type="xs:boolean" use="optional" />
													<xs:attribute name="categoryType" type="xs:string" use="optional" />
													<xs:attribute name="isHero" type="xs:boolean" use="optional" />
													<xs:attribute name="sex" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="pkCount" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="pledgeClass" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="level" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="subLevel" type="xs:unsignedShort" use="optional" />
													<xs:attribute name="races" type="xs:string" use="optional" />
													<xs:attribute name="clanHall" type="xs:string" use="optional" />
													<xs:attribute name="castle" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="SiegeZone" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="fort" type="xs:byte" use="optional" />
													<xs:attribute name="chaotic" type="xs:boolean" use="optional" />
													<xs:attribute name="instanceId" type="xs:string" use="optional" />
													<xs:attribute name="cloakStatus" type="xs:boolean" use="optional" />
													<xs:attribute name="levelRange" type="xs:string" use="optional" />
													<xs:attribute name="insideZoneId" type="xs:string" use="optional" />
													<xs:attribute name="vehicleMounted" type="xs:boolean" use="optional" />
													<xs:attribute name="MinimumVitalityPoints" type="xs:unsignedShort" use="optional" />
													<xs:attribute name="class_id_restriction" type="xs:string" use="optional" />
													<xs:attribute name="symbolsealpoints" type="xs:unsignedShort" use="optional" />
													<xs:attribute name="MaximumVitalityPoints" type="xs:unsignedInt" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="addName" type="xs:unsignedByte" use="optional" />
										<xs:attribute name="msgId" type="xs:unsignedShort" use="optional" />
									</xs:complexType>
								</xs:element>
								<xs:element name="capsuled_items">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="item">
												<xs:complexType>
													<xs:attribute name="id" type="xs:unsignedInt" use="required" />
													<xs:attribute name="min" type="xs:unsignedLong" use="required" />
													<xs:attribute name="max" type="xs:unsignedLong" use="required" />
													<xs:attribute name="chance" type="xs:decimal" use="required" />
													<xs:attribute name="minEnchant" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="maxEnchant" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="skills">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="skill">
												<xs:complexType>
													<xs:attribute name="id" type="xs:unsignedShort" use="required" />
													<xs:attribute name="level" type="xs:unsignedByte" use="required" />
													<xs:attribute name="subLevel" type="xs:unsignedShort" use="optional" />
													<xs:attribute name="type" type="xs:string" use="optional" />
													<xs:attribute name="type_value" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="type_chance" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="stats">
									<xs:complexType mixed="true">
										<xs:sequence minOccurs="0">
											<xs:element maxOccurs="unbounded" name="stat">
												<xs:complexType>
													<xs:simpleContent>
														<xs:extension base="xs:float">
															<xs:attribute name="type" type="xs:string" use="required" />
														</xs:extension>
													</xs:simpleContent>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedInt" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="additionalName" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aittiphon123/lineage2/L2J_Mobius_Essence_09.2_RoseVain/dist/game/data/stats/items/09500-09599.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="9589" name="Talisman Bracelet Lv. 1" type="Armor">
		<!-- <font color=bbaa88><Base effect></font>. Talisman slots +4. <font color=bbaa88><Compounding></font>. Materials: Talisman Bracelets and packages of the same level. In case of failure, the current level remains the same, but materials disappear. -->
		<set name="icon" val="icon.dimension_bracelet_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="rbracelet" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="SILVER" />
		<set name="weight" val="150" />
		<set name="price" val="1080000" />
		<set name="commissionItemType" val="BRACELET" />
		<set name="is_sellable" val="false" />
		<skills>
			<skill id="50192" level="1" /> <!-- Talisman Bracelet Lv. 1 -->
		</skills>
	</item>
	<item id="9590" name="Talisman Bracelet Lv. 2" type="Armor">
		<!-- <font color=bbaa88><Base effect></font>. Talisman slots +4. P. Atk. +20. M. Atk. +20. <font color=bbaa88><Compounding></font>. Materials: Talisman Bracelets and packages of the same level. In case of failure, the current level remains the same, but materials disappear. -->
		<set name="icon" val="icon.dimension_bracelet_i01" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="rbracelet" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="SILVER" />
		<set name="weight" val="150" />
		<set name="price" val="5400000" />
		<set name="commissionItemType" val="BRACELET" />
		<set name="is_sellable" val="false" />
		<skills>
			<skill id="50192" level="2" /> <!-- Talisman Bracelet Lv. 2 -->
		</skills>
	</item>
	<item id="9591" name="Talisman Bracelet Lv. 3" type="Armor">
		<!-- <font color=bbaa88><Base effect></font>. Talisman slots +4. P. Atk. +50. M. Atk. +50. <font color=bbaa88><Compounding></font>. Materials: Talisman Bracelets and packages of the same level. In case of failure, the current level remains the same, but materials disappear. -->
		<set name="icon" val="icon.dimension_bracelet_i02" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="rbracelet" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="SILVER" />
		<set name="weight" val="150" />
		<set name="price" val="27000000" />
		<set name="commissionItemType" val="BRACELET" />
		<set name="is_sellable" val="false" />
		<skills>
			<skill id="50192" level="3" /> <!-- Talisman Bracelet Lv. 3 -->
		</skills>
	</item>
</list>

=== aittiphon123/lineage2/L2J_Mobius_Classic_3.0_TheKamael/dist/game/data/stats/items/01700-01799.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="1785" name="Soulstone" type="EtcItem">
		<!-- Material required for using certain skills. -->
		<set name="icon" val="icon.etc_crystal_white_i00" />
		<set name="etcitem_type" val="MATERIAL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="price" val="250" />
		<set name="commissionItemType" val="OTHER_ITEM" />
		<set name="is_stackable" val="true" />
	</item>
	<item id="1786" name="Recipe: Broadsword" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Broadsword. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="250" />
		<set name="recipe_id" val="2" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1787" name="Recipe: Willow Staff" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Willow Staff. Requires Create Item Lv. 1 The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="250" />
		<set name="recipe_id" val="3" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1788" name="Recipe: Bow" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Bow. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="250" />
		<set name="recipe_id" val="4" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1789" name="Recipe: Cedar Staff" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Cedar Staff. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="1082" />
		<set name="recipe_id" val="5" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1790" name="Recipe: Dirk" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Dirk. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="1082" />
		<set name="recipe_id" val="6" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1791" name="Recipe: Brandish" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Brandish. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="1082" />
		<set name="recipe_id" val="7" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1792" name="Recipe: Short Spear" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Short Spear. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="2720" />
		<set name="recipe_id" val="8" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1793" name="Recipe: Sword of Reflection" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Sword of Reflection. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="2720" />
		<set name="recipe_id" val="9" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1794" name="Recipe: Forest Bow" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Forest Bow. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="2720" />
		<set name="recipe_id" val="10" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1795" name="Recipe: Leather Shoes" type="EtcItem">
		<!-- For Dwarves only. Recipe for Leather Shoes. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="53" />
		<set name="recipe_id" val="11" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1796" name="Recipe: Leather Tunic" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Leather Tunic. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="159" />
		<set name="recipe_id" val="12" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1797" name="Recipe: Leather Stockings" type="EtcItem">
		<!-- For Dwarves only. Recipe for Leather Stockings. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="99" />
		<set name="recipe_id" val="13" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1798" name="Recipe: Leather Helmet" type="EtcItem">
		<!-- For Dwarves only. Recipe for a Leather Helmet. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="204" />
		<set name="recipe_id" val="14" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
	<item id="1799" name="Recipe: Leather Gloves" type="EtcItem">
		<!-- For Dwarves only. Recipe for Leather Gloves. Requires Create Item Lv. 1. The success rate is 100%. -->
		<set name="icon" val="icon.etc_recipe_white_i00" />
		<set name="default_action" val="RECIPE" />
		<set name="etcitem_type" val="RECIPE" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="30" />
		<set name="price" val="135" />
		<set name="recipe_id" val="15" />
		<set name="is_stackable" val="true" />
		<set name="commissionItemType" val="RECIPE" />
		<set name="handler" val="Recipes" />
	</item>
</list>

=== aittiphon123/lineage2/L2J_Mobius_Classic_2.7_Antharas/dist/game/data/stats/items/00500-00599.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="500" name="Great Helmet" type="Armor">
		<set name="icon" val="icon.armor_helmet_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="head" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="96" />
		<set name="crystal_type" val="C" />
		<set name="material" val="FINE_STEEL" />
		<set name="weight" val="610" />
		<set name="price" val="242000" />
		<set name="commissionItemType" val="HELMET" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">51</stat>
		</stats>
	</item>
	<item id="503" name="Zubei's Helmet" type="Armor">
		<!-- Sealed Zubei's Helmet. The seal can be removed by a blacksmith in any village. -->
		<set name="icon" val="icon.armor_helmet_i02" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="head" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="96" />
		<set name="crystal_type" val="B" />
		<set name="material" val="MITHRIL" />
		<set name="weight" val="590" />
		<set name="price" val="778000" />
		<set name="commissionItemType" val="HELMET" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">62</stat>
		</stats>
	</item>
	<item id="512" name="Dark Crystal Helmet" type="Armor">
		<set name="icon" val="icon.armor_helmet_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="head" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="96" />
		<set name="crystal_type" val="A" />
		<set name="material" val="CRYSTAL" />
		<set name="weight" val="570" />
		<set name="price" val="1336000" />
		<set name="enchant_enabled" val="true" />
		<set name="commissionItemType" val="HELMET" />
		<stats>
			<stat type="pDef">69</stat>
		</stats>
	</item>
	<item id="517" name="Compound Helmet" type="Armor">
		<set name="icon" val="icon.armor_leather_helmet_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="head" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="147" />
		<set name="crystal_type" val="C" />
		<set name="material" val="FINE_STEEL" />
		<set name="weight" val="610" />
		<set name="price" val="368000" />
		<set name="commissionItemType" val="HELMET" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">54</stat>
		</stats>
	</item>
	<item id="547" name="Tallum Helmet" type="Armor">
		<set name="icon" val="icon.armor_helmet_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="head" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="147" />
		<set name="crystal_type" val="A" />
		<set name="material" val="CLOTH" />
		<set name="weight" val="570" />
		<set name="price" val="1336000" />
		<set name="enchant_enabled" val="true" />
		<set name="commissionItemType" val="HELMET" />
		<stats>
			<stat type="pDef">69</stat>
		</stats>
	</item>
	<item id="553" name="Iron Boots" type="Armor">
		<set name="icon" val="icon.armor_t10_b_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="92" />
		<set name="crystal_type" val="D" />
		<set name="material" val="FINE_STEEL" />
		<set name="weight" val="1280" />
		<set name="price" val="50800" />
		<set name="commissionItemType" val="FEET" />
		<set name="isAppearanceable" val="true" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">24</stat>
		</stats>
	</item>
	<item id="554" name="Sealed Zubei's Boots" type="Armor">
		<!-- Sealed Zubei's Boots. The seal can be removed by a blacksmith in any village. -->
		<set name="icon" val="icon.armor_t64_b_i02" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="69" />
		<set name="crystal_type" val="B" />
		<set name="material" val="MITHRIL" />
		<set name="weight" val="1180" />
		<set name="price" val="519000" />
		<set name="enchant_enabled" val="true" />
		<set name="isAppearanceable" val="true" />
		<set name="commissionItemType" val="FEET" />
		<stats>
			<stat type="pDef">41</stat>
		</stats>
	</item>
	<item id="563" name="Dark Crystal Boots" type="Armor">
		<set name="icon" val="icon.armor_t15_b_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="69" />
		<set name="crystal_type" val="A" />
		<set name="material" val="CRYSTAL" />
		<set name="weight" val="1110" />
		<set name="price" val="890000" />
		<set name="commissionItemType" val="FEET" />
		<set name="isAppearanceable" val="true" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">45</stat>
		</stats>
	</item>
	<item id="572" name="Boots of Silence" type="Armor">
		<set name="icon" val="icon.armor_t65_b_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="69" />
		<set name="crystal_type" val="B" />
		<set name="material" val="DAMASCUS" />
		<set name="weight" val="1190" />
		<set name="price" val="399100" />
		<set name="commissionItemType" val="FEET" />
		<set name="isAppearanceable" val="true" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">41</stat>
		</stats>
	</item>
	<item id="582" name="Paradia Boots" type="Armor">
		<set name="icon" val="icon.armor_t68_b_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="107" />
		<set name="crystal_type" val="B" />
		<set name="material" val="CHRYSOLITE" />
		<set name="weight" val="1140" />
		<set name="price" val="804000" />
		<set name="commissionItemType" val="FEET" />
		<set name="isAppearanceable" val="true" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">44</stat>
		</stats>
	</item>
	<item id="583" name="Majestic Boots" type="Armor">
		<set name="icon" val="icon.armor_t45_b_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="107" />
		<set name="crystal_type" val="A" />
		<set name="material" val="BLOOD_STEEL" />
		<set name="weight" val="1110" />
		<set name="price" val="1355000" />
		<set name="commissionItemType" val="FEET" />
		<set name="isAppearanceable" val="true" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">48</stat>
		</stats>
	</item>
	<item id="588" name="Elemental Boots" type="Armor">
		<set name="icon" val="icon.armor_t71_b_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="107" />
		<set name="crystal_type" val="B" />
		<set name="material" val="MITHRIL" />
		<set name="weight" val="1130" />
		<set name="price" val="804000" />
		<set name="commissionItemType" val="FEET" />
		<set name="isAppearanceable" val="true" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">44</stat>
		</stats>
	</item>
	<item id="590" name="Boots of Grace" type="Armor">
		<set name="icon" val="icon.armor_t71_b_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="107" />
		<set name="crystal_type" val="B" />
		<set name="material" val="MITHRIL" />
		<set name="weight" val="1130" />
		<set name="price" val="804000" />
		<set name="commissionItemType" val="FEET" />
		<set name="isAppearanceable" val="true" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">44</stat>
		</stats>
	</item>
	<item id="595" name="Boots of Blessing" type="Armor">
		<set name="icon" val="icon.armor_t56_b_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="69" />
		<set name="crystal_type" val="B" />
		<set name="material" val="ADAMANTAITE" />
		<set name="weight" val="1160" />
		<set name="price" val="519000" />
		<set name="commissionItemType" val="FEET" />
		<set name="isAppearanceable" val="true" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">41</stat>
		</stats>
	</item>
	<item id="598" name="Tallum Boots" type="Armor">
		<set name="icon" val="icon.armor_t45_b_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="feet" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_count" val="69" />
		<set name="crystal_type" val="A" />
		<set name="material" val="BLOOD_STEEL" />
		<set name="weight" val="1130" />
		<set name="price" val="890000" />
		<set name="commissionItemType" val="FEET" />
		<set name="isAppearanceable" val="true" />
		<set name="enchant_enabled" val="true" />
		<stats>
			<stat type="pDef">45</stat>
		</stats>
	</item>
</list>
