=== aittiphon123/lineage2/L2J_Mobius_13.2_WolfWaker/dist/game/data/xsd/skillTrees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="skillTree" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="skill" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="subClassConditions" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="slot" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:positiveInteger">
															<xs:minInclusive value="1" />
															<xs:maxInclusive value="3" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="lvl" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:positiveInteger">
															<xs:minInclusive value="1" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="removeSkill" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
												<xs:attribute name="onlyReplaceByLearn" type="xs:boolean" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="socialClass" minOccurs="0" maxOccurs="1">
											<xs:simpleType>
												<xs:restriction base="xs:token">
													<xs:enumeration value="VAGABOND" />
													<xs:enumeration value="VASSAL" />
													<xs:enumeration value="APPRENTICE" />
													<xs:enumeration value="HEIR" />
													<xs:enumeration value="KNIGHT" />
													<xs:enumeration value="ELDER" />
													<xs:enumeration value="BARON" />
													<xs:enumeration value="VISCOUNT" />
													<xs:enumeration value="COUNT" />
													<xs:enumeration value="MARQUIS" />
													<xs:enumeration value="DUKE" />
													<xs:enumeration value="GRAND_DUKE" />
													<xs:enumeration value="DISTINGUISHED_KING" />
													<xs:enumeration value="EMPEROR" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="residenceId" minOccurs="0" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:positiveInteger">
													<xs:minInclusive value="1" />
													<xs:maxInclusive value="200" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="race" minOccurs="0" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:token">
													<xs:enumeration value="HUMAN" />
													<xs:enumeration value="ELF" />
													<xs:enumeration value="DARK_ELF" />
													<xs:enumeration value="ORC" />
													<xs:enumeration value="DWARF" />
													<xs:enumeration value="KAMAEL" />
													<xs:enumeration value="ERTHEIA" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="preRequisiteSkill" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
												<xs:attribute name="lvl" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="item" minOccurs="0" maxOccurs="2">
											<xs:complexType>
												<xs:attribute name="id" type="xs:normalizedString" use="required" />
												<xs:attribute name="count" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="autoGet" type="xs:boolean" />
									<xs:attribute name="getLevel">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="getDualClassLevel">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="learnedByFS" type="xs:boolean" />
									<xs:attribute name="learnedByNpc" type="xs:boolean" />
									<xs:attribute name="levelUpSp" type="xs:long" />
									<xs:attribute name="residenceSkill" type="xs:boolean" />
									<xs:attribute name="skillId" type="xs:positiveInteger" use="required" />
									<xs:attribute name="skillLevel" type="xs:positiveInteger" use="required" />
									<xs:attribute name="skillName" type="xs:normalizedString" use="required" />
									<xs:attribute name="treeId" type="xs:positiveInteger" />
									<xs:attribute name="row" type="xs:positiveInteger" />
									<xs:attribute name="column" type="xs:positiveInteger" />
									<xs:attribute name="pointsRequired" type="xs:positiveInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="classId">
							<xs:simpleType>
								<xs:restriction base="xs:nonNegativeInteger">
									<xs:minInclusive value="0" />
									<xs:maxInclusive value="259" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="parentClassId">
							<xs:simpleType>
								<xs:restriction base="xs:nonNegativeInteger">
									<xs:minInclusive value="0" />
									<xs:maxInclusive value="259" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="abilitySkillTree" />
									<xs:enumeration value="alchemySkillTree" />
									<xs:enumeration value="awakeningSaveSkillTree" />
									<xs:enumeration value="classSkillTree" />
									<xs:enumeration value="collectSkillTree" />
									<xs:enumeration value="dualClassSkillTree" />
									<xs:enumeration value="fishingSkillTree" />
									<xs:enumeration value="gameMasterAuraSkillTree" />
									<xs:enumeration value="gameMasterSkillTree" />
									<xs:enumeration value="heroSkillTree" />
									<xs:enumeration value="nobleSkillTree" />
									<xs:enumeration value="pledgeSkillTree" />
									<xs:enumeration value="raceSkillTree" />
									<xs:enumeration value="revelationSkillTree" />
									<xs:enumeration value="subClassSkillTree" />
									<xs:enumeration value="subClassChangeSkillTree" />
									<xs:enumeration value="subPledgeSkillTree" />
									<xs:enumeration value="transferSkillTree" />
									<xs:enumeration value="transformSkillTree" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="race" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="HUMAN" />
									<xs:enumeration value="ELF" />
									<xs:enumeration value="DARK_ELF" />
									<xs:enumeration value="ORC" />
									<xs:enumeration value="DWARF" />
									<xs:enumeration value="KAMAEL" />
									<xs:enumeration value="ERTHEIA" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="subType" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="BASECLASS" />
									<xs:enumeration value="DUALCLASS" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aittiphon123/lineage2/L2J_Mobius_Classic_2.9.5_Saviors/dist/game/data/stats/players/skillTrees/3rdClass/SpectralDancer.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="107" parentClassId="34">
		<skill skillName="Arrest" skillId="402" skillLevel="11" getLevel="76" levelUpSp="7600000" />
		<skill skillName="Divine Inspiration" skillId="1405" skillLevel="3" getLevel="76" levelUpSp="7600000">
			<item id="8620" count="1" /> <!-- Ancient Book: Divine Inspiration (Manuscript) -->
		</skill>
		<skill skillName="Divine Inspiration" skillId="1405" skillLevel="4" getLevel="76" levelUpSp="7600000">
			<item id="8621" count="1" /> <!-- Ancient Book: Divine Inspiration (Original Version) -->
		</skill>
		<skill skillName="Dual Weapon Mastery" skillId="144" skillLevel="38" getLevel="76" levelUpSp="7600000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="53" getLevel="76" levelUpSp="7600000" />
		<skill skillName="Sting" skillId="223" skillLevel="50" getLevel="76" levelUpSp="7600000" />
		<skill skillName="Freezing Strike" skillId="105" skillLevel="25" getLevel="76" levelUpSp="7600000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="54" getLevel="76" levelUpSp="7600000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="52" getLevel="76" levelUpSp="7600000" />
		<skill skillName="Mount Saber Tooth Cougar" skillId="1835" skillLevel="1" getLevel="76">
			<item id="90040" count="1" /> <!-- Spellbook: Mount Saber Tooth Cougar -->
		</skill>
		<skill skillName="Hex" skillId="122" skillLevel="16" getLevel="76" levelUpSp="7600000" />
		<skill skillName="Deadly Strike" skillId="1632" skillLevel="1" getLevel="76" levelUpSp="7600000" />
		<skill skillName="Power Break" skillId="115" skillLevel="18" getLevel="76" levelUpSp="7600000" />
		
		<skill skillName="Dual Weapon Mastery" skillId="144" skillLevel="39" getLevel="77" levelUpSp="7600000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="54" getLevel="77" levelUpSp="7600000" />
		<skill skillName="Sting" skillId="223" skillLevel="51" getLevel="77" levelUpSp="7600000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="55" getLevel="77" levelUpSp="7600000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="53" getLevel="77" levelUpSp="7600000" />
		<skill skillName="Deadly Strike" skillId="1632" skillLevel="2" getLevel="77" levelUpSp="7600000" />
		<skill skillName="Dance of Shadows" skillId="366" skillLevel="1" getLevel="77" levelUpSp="7600000">
			<item id="90094" count="1" /> <!-- Scroll: Dance of Shadows -->
		</skill>
		
		<skill skillName="Arrest" skillId="402" skillLevel="12" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Dual Weapon Mastery" skillId="144" skillLevel="40" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="55" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Sting" skillId="223" skillLevel="52" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Freezing Strike" skillId="105" skillLevel="26" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="56" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="54" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Hex" skillId="122" skillLevel="17" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Deadly Strike" skillId="1632" skillLevel="3" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Power Break" skillId="115" skillLevel="19" getLevel="78" levelUpSp="17800000" />
		<skill skillName="Dance of Siren" skillId="365" skillLevel="1" getLevel="78" levelUpSp="17800000">
			<item id="90095" count="1" /> <!-- Scroll: Dance of Siren -->
		</skill>
		<skill skillName="Poison Blade Dance" skillId="84" skillLevel="4" getLevel="78" levelUpSp="17800000" />

		<skill skillName="Dance of Medusa" skillId="367" skillLevel="1" getLevel="79" levelUpSp="17800000">
			<item id="90096" count="1" /> <!-- Scroll: Dance of Medusa -->
		</skill>
		
		<skill skillName="Dual Weapon Mastery" skillId="144" skillLevel="41" getLevel="80" levelUpSp="17800000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="56" getLevel="80" levelUpSp="17800000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="55" getLevel="80" levelUpSp="17800000" />
		<skill skillName="Deadly Strike" skillId="1632" skillLevel="4" getLevel="80" levelUpSp="17800000" />
		<skill skillName="Dance of Berserker" skillId="915" skillLevel="1" getLevel="80" levelUpSp="17800000">
			<item id="90097" count="1" /> <!-- Scroll: Dance of Berserker -->
		</skill>
		
		<skill skillName="Dual Weapon Mastery" skillId="144" skillLevel="42" getLevel="81" levelUpSp="160000000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="57" getLevel="81" levelUpSp="160000000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="56" getLevel="81" levelUpSp="160000000" />
		<skill skillName="Deadly Strike" skillId="1632" skillLevel="5" getLevel="81" levelUpSp="160000000" />
		<skill skillName="Dance of Medusa" skillId="367" skillLevel="2" getLevel="81" levelUpSp="160000000" />
		<skill skillName="Dance of Shadows" skillId="366" skillLevel="2" getLevel="81" levelUpSp="160000000" />
		<skill skillName="Dance of Fury" skillId="275" skillLevel="2" getLevel="81" levelUpSp="160000000" />

		<skill skillName="Dual Weapon Mastery" skillId="144" skillLevel="43" getLevel="82" levelUpSp="170000000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="58" getLevel="82" levelUpSp="170000000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="57" getLevel="82" levelUpSp="170000000" />
		<skill skillName="Deadly Strike" skillId="1632" skillLevel="6" getLevel="82" levelUpSp="170000000" />
		<skill skillName="Dance of Concentration" skillId="276" skillLevel="2" getLevel="82" levelUpSp="170000000" />

		<skill skillName="Dual Weapon Mastery" skillId="144" skillLevel="44" getLevel="83" levelUpSp="240000000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="59" getLevel="83" levelUpSp="240000000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="58" getLevel="83" levelUpSp="240000000" />
		<skill skillName="Deadly Strike" skillId="1632" skillLevel="7" getLevel="83" levelUpSp="240000000" />
		<skill skillName="Dance of Medusa" skillId="367" skillLevel="3" getLevel="83" levelUpSp="240000000" />
		<skill skillName="Dance of Siren" skillId="365" skillLevel="2" getLevel="83" levelUpSp="240000000" />

		<skill skillName="Dual Weapon Mastery" skillId="144" skillLevel="45" getLevel="84" levelUpSp="240000000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="60" getLevel="84" levelUpSp="240000000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="59" getLevel="84" levelUpSp="240000000" />
		<skill skillName="Deadly Strike" skillId="1632" skillLevel="8" getLevel="84" levelUpSp="240000000" />
		<skill skillName="Dance of Shadows" skillId="366" skillLevel="3" getLevel="84" levelUpSp="240000000" />
		<skill skillName="Poison Blade Dance" skillId="84" skillLevel="5" getLevel="84" levelUpSp="240000000" />
		
		<skill skillName="Dual Weapon Mastery" skillId="144" skillLevel="46" getLevel="85" levelUpSp="840000000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="61" getLevel="85" levelUpSp="840000000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="60" getLevel="85" levelUpSp="840000000" />
	</skillTree>
</list>

=== aittiphon123/lineage2/L2J_Mobius_Essence_04.2_DwellingOfSpirits/dist/game/data/stats/players/skillTrees/Kamael/KamaelSoldier.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="192">

		<skill skillName="Armor Mastery" skillId="464" skillLevel="1" getLevel="1" autoGet="true" />
		<skill skillName="Weapon Mastery" skillId="463" skillLevel="1" getLevel="1" autoGet="true" />
		<skill skillName="Kamael's Dignity" skillId="328" skillLevel="1" getLevel="1" autoGet="true" />
		<skill skillName="Expand Inventory" skillId="1372" skillLevel="1" getLevel="1">
			<item id="92004" count="1" /> <!-- Inventory Expansion Coupon Lv. 1 -->
		</skill>
		<skill skillName="Expand Inventory" skillId="1372" skillLevel="2" getLevel="1">
			<item id="92005" count="1" /> <!-- Inventory Expansion Coupon Lv. 2 -->
		</skill>
		<skill skillName="Expand Inventory" skillId="1372" skillLevel="3" getLevel="1">
			<item id="92006" count="1" /> <!-- Inventory Expansion Coupon Lv. 3 -->
		</skill>
		<skill skillName="Expand Inventory" skillId="1372" skillLevel="4" getLevel="1">
			<item id="92007" count="1" /> <!-- Inventory Expansion Coupon Lv. 4 -->
		</skill>
		<skill skillName="Expand Inventory" skillId="1372" skillLevel="5" getLevel="1">
			<item id="92008" count="1" /> <!-- Inventory Expansion Coupon Lv. 5 -->
		</skill>
		<skill skillName="Pride of Kamael" skillId="329" skillLevel="1" getLevel="1" autoGet="true" />

		<skill skillName="Soul Shield" skillId="45145" skillLevel="1" getLevel="2" levelUpSp="5" />

		<skill skillName="Soul Might" skillId="45144" skillLevel="1" getLevel="3" levelUpSp="5" />

		<skill skillName="Ability to Protect" skillId="91" skillLevel="1" getLevel="5" levelUpSp="15" />

		<skill skillName="Ability to Attack" skillId="77" skillLevel="1" getLevel="10" levelUpSp="100" />
		<skill skillName="Emergency Rescue" skillId="70" skillLevel="1" getLevel="10" levelUpSp="100" />

		<skill skillName="Death Mark" skillId="1435" skillLevel="1" getLevel="15" levelUpSp="500" />
		<skill skillName="Emergency Rescue" skillId="70" skillLevel="2" getLevel="15" levelUpSp="500" />
	</skillTree>
</list>

=== aittiphon123/lineage2/L2J_Mobius_Classic_2.7_Antharas/dist/game/data/stats/players/skillTrees/1stClass/PalusKnight.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="32" parentClassId="31">
		<skill skillName="Sword/Blunt Weapon Mastery" skillId="217" skillLevel="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="2" getLevel="20" levelUpSp="1000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="3" getLevel="20" levelUpSp="1000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="2" getLevel="20" levelUpSp="1000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="3" getLevel="20" levelUpSp="1000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="4" getLevel="20" levelUpSp="1000" />
		<skill skillName="Defense Aura" skillId="91" skillLevel="2" getLevel="20" levelUpSp="1000" />
		<skill skillName="Shield Mastery" skillId="153" skillLevel="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Ultimate Defense" skillId="110" skillLevel="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Poison" skillId="129" skillLevel="1" getLevel="20" levelUpSp="1000" />
		
		<skill skillName="Aggression" skillId="28" skillLevel="1" getLevel="22" levelUpSp="2800" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="4" getLevel="22" levelUpSp="2800" />
		<skill skillName="Sting" skillId="223" skillLevel="1" getLevel="22" levelUpSp="2800" />
		<skill skillName="Drain HP" skillId="70" skillLevel="5" getLevel="22" levelUpSp="2800" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="3" getLevel="22" levelUpSp="2800" />
		
		<skill skillName="Aggression" skillId="28" skillLevel="2" getLevel="23" levelUpSp="2800" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="5" getLevel="23" levelUpSp="2800" />
		<skill skillName="Sting" skillId="223" skillLevel="2" getLevel="23" levelUpSp="2800" />
		<skill skillName="Drain HP" skillId="70" skillLevel="6" getLevel="23" levelUpSp="2800" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="4" getLevel="23" levelUpSp="2800" />
		
		<skill skillName="Sword/Blunt Weapon Mastery" skillId="217" skillLevel="2" getLevel="24" levelUpSp="2800" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="6" getLevel="24" levelUpSp="2800" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="5" getLevel="24" levelUpSp="2800" />
		<skill skillName="Drain HP" skillId="70" skillLevel="7" getLevel="24" levelUpSp="2800" />
		<skill skillName="Aggression" skillId="28" skillLevel="3" getLevel="24" levelUpSp="2800" />
		<skill skillName="Sting" skillId="223" skillLevel="3" getLevel="24" levelUpSp="2800" />
		<skill skillName="Deflect Arrow" skillId="112" skillLevel="1" getLevel="24" levelUpSp="2800" />
		<skill skillName="Confusion" skillId="2" skillLevel="1" getLevel="24" levelUpSp="2800" />
		
		<skill skillName="Aggression" skillId="28" skillLevel="4" getLevel="26" levelUpSp="5700" />
		<skill skillName="Sword/Blunt Weapon Mastery" skillId="217" skillLevel="3" getLevel="26" levelUpSp="5700" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="7" getLevel="26" levelUpSp="5700" />
		<skill skillName="Sting" skillId="223" skillLevel="4" getLevel="26" levelUpSp="5700" />
		<skill skillName="Drain HP" skillId="70" skillLevel="8" getLevel="26" levelUpSp="5700" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="6" getLevel="26" levelUpSp="5700" />
		
		<skill skillName="Aggression" skillId="28" skillLevel="5" getLevel="27" levelUpSp="5700" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="8" getLevel="27" levelUpSp="5700" />
		<skill skillName="Sting" skillId="223" skillLevel="5" getLevel="27" levelUpSp="5700" />
		<skill skillName="Drain HP" skillId="70" skillLevel="9" getLevel="27" levelUpSp="5700" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="7" getLevel="27" levelUpSp="5700" />
		
		<skill skillName="Sword/Blunt Weapon Mastery" skillId="217" skillLevel="4" getLevel="28" levelUpSp="5700" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="9" getLevel="28" levelUpSp="5700" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="8" getLevel="28" levelUpSp="5700" />
		<skill skillName="Drain HP" skillId="70" skillLevel="10" getLevel="28" levelUpSp="5700" />
		<skill skillName="Aggression" skillId="28" skillLevel="6" getLevel="28" levelUpSp="5700" />
		<skill skillName="Sting" skillId="223" skillLevel="6" getLevel="28" levelUpSp="5700" />
		<skill skillName="Shield Mastery" skillId="153" skillLevel="2" getLevel="28" levelUpSp="5700" />
		<skill skillName="Confusion" skillId="2" skillLevel="2" getLevel="28" levelUpSp="5700" />
		<skill skillName="Attack Aura" skillId="77" skillLevel="2" getLevel="28" levelUpSp="5700" />
		
		<skill skillName="Aggression" skillId="28" skillLevel="7" getLevel="30" levelUpSp="11000" />
		<skill skillName="Sword/Blunt Weapon Mastery" skillId="217" skillLevel="5" getLevel="30" levelUpSp="11000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="10" getLevel="30" levelUpSp="11000" />
		<skill skillName="Sting" skillId="223" skillLevel="7" getLevel="30" levelUpSp="11000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="11" getLevel="30" levelUpSp="11000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="9" getLevel="30" levelUpSp="11000" />
		
		<skill skillName="Aggression" skillId="28" skillLevel="8" getLevel="31" levelUpSp="11000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="11" getLevel="31" levelUpSp="11000" />
		<skill skillName="Sting" skillId="223" skillLevel="8" getLevel="31" levelUpSp="11000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="12" getLevel="31" levelUpSp="11000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="10" getLevel="31" levelUpSp="11000" />
		
		<skill skillName="Sword/Blunt Weapon Mastery" skillId="217" skillLevel="6" getLevel="32" levelUpSp="11000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="12" getLevel="32" levelUpSp="11000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="11" getLevel="32" levelUpSp="11000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="13" getLevel="32" levelUpSp="11000" />
		<skill skillName="Aggression" skillId="28" skillLevel="9" getLevel="32" levelUpSp="11000" />
		<skill skillName="Sting" skillId="223" skillLevel="9" getLevel="32" levelUpSp="11000" />
		<skill skillName="Deflect Arrow" skillId="112" skillLevel="2" getLevel="32" levelUpSp="11000" />
		<skill skillName="Confusion" skillId="2" skillLevel="3" getLevel="32" levelUpSp="11000" />
		<skill skillName="Power Break" skillId="115" skillLevel="1" getLevel="32" levelUpSp="11000">
			<item id="1382" count="1" />
		</skill>
		
		<skill skillName="Aggression" skillId="28" skillLevel="10" getLevel="34" levelUpSp="20000" />
		<skill skillName="Sword/Blunt Weapon Mastery" skillId="217" skillLevel="7" getLevel="34" levelUpSp="20000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="13" getLevel="34" levelUpSp="20000" />
		<skill skillName="Sting" skillId="223" skillLevel="10" getLevel="34" levelUpSp="20000" />
		<skill skillName="Freezing Strike" skillId="105" skillLevel="1" getLevel="34" levelUpSp="20000">
			<item id="1381" count="1" />
		</skill>
		<skill skillName="Drain HP" skillId="70" skillLevel="14" getLevel="34" levelUpSp="20000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="12" getLevel="34" levelUpSp="20000" />
		
		<skill skillName="Aggression" skillId="28" skillLevel="11" getLevel="35" levelUpSp="20000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="14" getLevel="35" levelUpSp="20000" />
		<skill skillName="Sting" skillId="223" skillLevel="11" getLevel="35" levelUpSp="20000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="15" getLevel="35" levelUpSp="20000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="13" getLevel="35" levelUpSp="20000" />
		
		<skill skillName="Sword/Blunt Weapon Mastery" skillId="217" skillLevel="8" getLevel="36" levelUpSp="20000" />
		<skill skillName="Heavy Armor Mastery" skillId="232" skillLevel="15" getLevel="36" levelUpSp="20000" />
		<skill skillName="Magic Resistance" skillId="147" skillLevel="14" getLevel="36" levelUpSp="20000" />
		<skill skillName="Drain HP" skillId="70" skillLevel="16" getLevel="36" levelUpSp="20000" />
		<skill skillName="Aggression" skillId="28" skillLevel="12" getLevel="36" levelUpSp="20000" />
		<skill skillName="Sting" skillId="223" skillLevel="12" getLevel="36" levelUpSp="20000" />
		<skill skillName="Freezing Strike" skillId="105" skillLevel="2" getLevel="36" levelUpSp="20000" />
		<skill skillName="Focus Mind" skillId="191" skillLevel="1" getLevel="36" levelUpSp="20000" />
		<skill skillName="Confusion" skillId="2" skillLevel="4" getLevel="36" levelUpSp="20000" />
		<skill skillName="Power Break" skillId="115" skillLevel="2" getLevel="36" levelUpSp="20000" />
	</skillTree>
</list>
